Update pipeline.yml

diff --git a/.bluemix/pipeline.yml b/.bluemix/pipeline.yml
--- a/.bluemix/pipeline.yml
+++ b/.bluemix/pipeline.yml
@@ -74,50 +74,215 @@ stages:
       #!/bin/bash
       #mvn -B package -e -Pbluemix
       mvn -B package -e 
-      cp -r ${WORKSPACE}/wlp ${WORKSPACE}/AIFParent/AIF/target/wlp    
+      cp -r ${WORKSPACE}/wlp ${WORKSPACE}/AIFParent/AIF/target/wlp
       
-- name: Deploy Stage(AIF)
+      cp -r ${WORKSPACE}/dockerfiles ${WORKSPACE}/AIFParent/AIF/target/dockerfiles
+      ls ${WORKSPACE}/AIFParent/AIF/target/wlp  
+
+- name: Build Stage (AIF Container)
   inputs:
   - type: job
     stage: Build Stage(AIF)
     job: Build
+  triggers:
+  - type: commit
+  properties:
+  - name: JAVA_HOME
+    value: /opt/IBM/java8
+    type: text
+  jobs:
+  - name: Container build
+    type: builder
+    extension_id: ibm.devops.services.pipeline.container.builder
+    target:
+      region_id: ${PROD_REGION_ID}
+      organization: ${PROD_ORG_NAME}
+      space: ${PROD_SPACE_NAME}
+    IMAGE_NAME: ${AIF_APP_NAME}
+    USE_CACHED_LAYERS: 'true'
+    COMMAND: |
+      #!/bin/bash
+
+      echo -------------start server packaging---------------------
+      #!/bin/bash
+      #サーバーパッケージ
+      cp AIF-1.0.1.war wlp/usr/servers/defaultServer/apps/AIF-1.0.1.war
+      chmod +x wlp/bin/*
+      wlp/bin/server package defaultServer --archive=was.zip --include=usr
+      
+      cp wlp/usr/servers/defaultServer/was.zip dockerfiles/was.zip
+      
+      
+      echo -------------start conatiner building-------------------
+      
+      if [ $(cf ic images | grep ${APP_NAME}  | wc -l) -gt 0 ]; then
+       echo -e "${red}Image ${APP_NAME} exists in the registory, delete it and re-upload as anew version of the image.${no_color}"
+       cf ic rmi $(cf ic images | grep ${APP_NAME} | awk '{print $3}')
+      else
+       echo "Image ${APP_NAME} doesn't exist."
+      fi
+      # The following colors have been defined to help with presentation of logs: green, red, label_color, no_color.  
+      echo -e "${label_color}Starting build script${no_color}"
+      # The IBM Container Service CLI (ice), Git client (git), IDS Inventory CLI (ids-inv) and Python 2.7.3 (python) have been installed.
+      # Based on the organization and space selected in the Job credentials are in place for both IBM Container Service and IBM Bluemix 
+      #####################
+      # Run unit tests    #
+      #####################
+      echo -e "${label_color}No unit tests cases have been checked in ${no_color}"
+      
+      ######################################
+      # Build Container via Dockerfile     #
+      ######################################
+
+      # REGISTRY_URL=${CCS_REGISTRY_HOST}/${NAMESPACE}
+      export FULL_REPOSITORY_NAME=${REGISTRY_URL}/${IMAGE_NAME}:latest  
+      cd dockerfiles
+      # Possible adding retries to build the image
+      if [ -f Dockerfile ]; then 
+          echo -e "${label_color}BUILDING ${FULL_REPOSITORY_NAME} ${no_color}"
+          ${EXT_DIR}/utilities/sendMessage.sh -l info -m "New container build requested for ${FULL_REPOSITORY_NAME}"
+          # build image
+          BUILD_COMMAND=""
+          if [ "${USE_CACHED_LAYERS}" == "true" ]; then 
+              BUILD_COMMAND="build --pull --tag ${FULL_REPOSITORY_NAME} ${WORKSPACE}/dockerfiles"
+              ice_retry ${BUILD_COMMAND}
+              RESULT=$?
+          else 
+              BUILD_COMMAND="build --no-cache --tag ${FULL_REPOSITORY_NAME} ${WORKSPACE}/dockerfiles"
+              ice_retry ${BUILD_COMMAND}
+              RESULT=$?
+          fi 
+  
+          if [ $RESULT -ne 0 ]; then
+              echo -e "${red}Error building image ${no_color}" | tee -a "$ERROR_LOG_FILE"
+              echo "Build command: ice ${BUILD_COMMAND}"
+              ice info 
+              ice images
+              ${EXT_DIR}/print_help.sh
+              ${EXT_DIR}/utilities/sendMessage.sh -l bad -m "Container build of ${FULL_REPOSITORY_NAME} failed"
+              exit 1
+          else
+              ${EXT_DIR}/utilities/sendMessage.sh -l good -m "Container build of ${FULL_REPOSITORY_NAME} was successful"
+              echo -e "${green}Container build of ${FULL_REPOSITORY_NAME} was successful ${no_color}"
+          fi  
+      else 
+          echo -e "${red}Dockerfile not found at the repository root${no_color}"
+          exit 1
+      fi  
+
+      ######################################################################################
+      # Copy any artifacts that will be needed for deployment and testing to $WORKSPACE    #
+      ######################################################################################
+      echo "IMAGE_NAME=${FULL_REPOSITORY_NAME}" >> $ARCHIVE_DIR/build.properties
+      if [ -f deployment.yml ]; then
+          #Update deployment.yml with image name
+          echo "UPDATING DEPLOYMENT MANIFEST:"
+          sed -i "s~^\([[:blank:]]*\)image:.*$~\1image: ${FULL_REPOSITORY_NAME}~" deployment.yml
+          cat deployment.yml
+          cp deployment.yml $ARCHIVE_DIR/
+      else 
+          echo -e "${red}Kubernetes deployment file 'deployment.yml' not found at the repository root${no_color}"
+          exit 1
+      fi
+      
+- name: Deploy Stage(AIF)
+  inputs:
+  - type: job
+    stage: Build Stage (AIF Container)
+    job: Container build
   triggers:
   - type: stage
   properties:
   - name: JAVA_HOME
     value: /opt/IBM/java8
     type: text
-  - name: STUB_APP_URL
-    value: ${STUB_APP_URL}
+  - name: APP_PORT
+    value: ${APP_PORT}
     type: text
-  properties:
-  jobs:
-  - name: Deploy
+  - name: APP_NAME
+    value: ${AIF_APP_NAME}
+    type: text
+  - name: CLOUDANT_URL
+    value: ${CLOUDANT_URL}
+    type: text
+  - name: MQ_REGISTORY
+    value: registry.ng.bluemix.net/ibmcom/mq
+    type: text 
+   jobs:
+  - name: Deploy Kubernetes Pod
     type: deployer
     target:
       region_id: ${PROD_REGION_ID}
       organization: ${PROD_ORG_NAME}
       space: ${PROD_SPACE_NAME}
-      application: AIF
+      api_key: ${API_KEY}
+      kubernetes_cluster: ${PROD_CLUSTER_NAME}
     script: |
       #!/bin/bash
-      #サーバーパッケージ
-      cp AIF-0.0.1-SNAPSHOT.war wlp/usr/servers/defaultServer/apps/AIF-1.0.1.war
-      chmod +x wlp/bin/*
-      wlp/bin/server package defaultServer --archive=was.zip --include=usr
-      # アプリのデプロイ、更新
-      #
-      cf push "${CF_APP}" -p wlp/usr/servers/defaultServer/was.zip -m 1024M -t 180 --no-start
-      # Liberty用の環境設定
-      cf set-env ${CF_APP} JBP_CONFIG_LIBERTY "app_archive: {features: [cdi-1.2, concurrent-1.0, jaxb-2.2, jndi-1.0, jaxws-2.2, jsonp-1.0, jaxrs-2.0, javaMail-1.5, json-1.0, jsf-2.2, localConnector-1.0, servlet-3.1, wasJmsClient-2.0, wasJmsServer-1.0, websocket-1.1,wmqJmsClient-2.0]}"
-      # システム変数定義
-      cf set-env ${CF_APP} JVM_ARGS "-Dcom.ibm.cis.aif.log.AIFLogger.isDumpEnable=true -Dcom.ibm.cis.aif.log.AIFLogger.vcapServiceName=cloudantNoSQLDB"
-      # MQ電文でMQコンテナを使用しない場合のStubAppRSのURL指定(MQコンテナを使用する場合はコメントアウトのままでOK)
-      #cf set-env ${CF_APP} JVM_ARGS " -Dcom.ibm.cis.aif.interceptor.OBStub.restStub=${STUB_APP_URL}"
-      # 上記設定の反映
-      cf restage ${CF_APP}
-      # アプリの起動
-      cf start ${CF_APP}
+      #set -x
+      
+      #Check cluster availability
+      ip_addr=$(bx cs workers $PIPELINE_KUBERNETES_CLUSTER_NAME | grep normal | awk '{ print $2 }')
+      if [ -z $ip_addr ]; then
+       echo "$PIPELINE_KUBERNETES_CLUSTER_NAME not created or workers not ready"
+       exit 1
+      fi
+      #Connect to a different container-service api by uncommenting and specifying an api endpoint
+      #bx cs init --host https://us-south.containers.bluemix.net
+      echo ""
+      echo "DEPLOYING USING MANIFEST:"
+      cd ${WORKSPACE}/dockerfiles
+      
+      registory=$(bx cr images | grep ${APP_NAME} | awk '{print $1":"$3}')
+      sed -i -e "s|REGISTORY|${registory}|g;s|APPNAME|${APP_NAME}-v${IDS_VERSION}|g;s|APPPORT|${APP_PORT}|g" ${WORKSPACE}/dockerfiles/deployment.yml
+      
+      cat ${WORKSPACE}/dockerfiles/deployment.yml
+      echo $(kubectl get deploy | grep ${APP_NAME} |wc -l)
+      if [ $(kubectl get deploy | grep ${APP_NAME} |wc -l) -gt 0 ]; then
+       echo -e "${red} ${APP_NAME} has been deployed. Will be rolling-updated. ${no_color}"
+       #kubectl delete deploy ${APP_NAME}
+       #kubectl delete svc ${APP_NAME}-service
+      else
+       echo No deploy has deteced. ${APP_NAME} will be deployed.
+      fi
+      
+      kubectl apply -f ${WORKSPACE}/dockerfiles/deployment.yml 
+      
+      if [ $(kubectl get deploy | grep MQ |wc -l) -gt 0 ]; then
+       echo -e "${red} MQ daployment has already been deployed. ${no_color}"
+      else
+       echo No MQ deployment has deteced. MQ will be deployed.
+       kubectl run MQ --image=${MQ_REGISTORY}
+       kubectl expose deployment/MQ --type=NodePort --port=1414 --name=mq-service --target-port=1414
+      fi
+      
+      echo ""
+      echo "DEPLOYED SERVICE:"
+      kubectl describe services ${APP_NAME}-service
+      
+      echo ""
+      echo "DEPLOYED PODS:"
+      kubectl describe pods --selector app=${APP_NAME}
+      
+      port=$(kubectl get services | grep ${APP_NAME}-service | sed 's/.*:\([0-9]*\).*/\1/g')
+      mq_port=$(kubectl get services | grep mq-service | sed 's/.*:\([0-9]*\).*/\1/g')  
+      echo ""
+      echo "VIEW THE APPLICATION AT: http://$ip_addr:$port"
+      
+      if [ $(curl -s -X PUT ${CLOUDANT_URL}/kubernetescredential | grep "ok" | wc -l) -gt 0 ];then
+       echo "kubernetescredential table created"
+      fi
+      
+      if [ -z $(curl -s -X GET ${CLOUDANT_URL}/kubernetescredential/kubecred --head | grep 'ETag' | awk -F\" '{print $2}') ];then
+       echo "kubecred file hadn't been created."
+      else
+       echo "The record kubecred is deteced."
+       curl -s -X DELETE ${CLOUDANT_URL}/kubernetescredential/kubecred?rev=$(curl -s -X GET ${CLOUDANT_URL}/kubernetescredential/kubecred --head | grep 'ETag' | awk -F\" '{print $2}')
+      fi
+      
+      json={\"aif_url\":\"http://${ip_addr}\",\"aif_port\":\"${port}\",\"mq_port\":\"${mq_port}\" }
+      echo $json
+      curl -X PUT ${CLOUDANT_URL}/kubernetescredential/kubecred -d ${json}
 
 - name: setEnv
   inputs:
@@ -133,8 +298,8 @@ stages:
   - name: PATH
     value: ${JAVA_HOME}/bin:$PATH
     type: text
-  - name: AIF_URL
-    value: ${AIF_URL}
+  - name: CLOUDANT_URL
+    value: ${CLOUDANT_URL}
     type: text
   jobs:
   - name: Build
@@ -144,9 +309,17 @@ stages:
     build_type: maven
     script: |-
       #!/bin/bash
-      URL=${AIF_URL}/aif
+      AIF_URL=$(curl -X GET ${CLOUDANT_URL}/kubernetescredential/kubecred | awk -F\"aif_url\" '{print $2}' | awk -F\" '{print $2}')
+      AIF_PORT=$(curl -X GET ${CLOUDANT_URL}/kubernetescredential/kubecred | awk -F\"aif_port\" '{print $2}' | awk -F\" '{print $2}')
+      
+      APP_URL=${AIF_URL}:${AIF_PORT}
+      echo -----$APP_URL
+      
+      URL=${APP_URL}/aif
       LIST=${WORKSPACE}/SFDParent/SFDEnvSet/URIConvert/BluemixConvertList.txt
+      
       mvn install
+      
       # 実行
       java -cp "${ARCHIVE_DIR}/lib/*" com.ibm.cis.aif.sfd.URIConverter.OutboundURIConverter "$LIST" "$URL"
 
@@ -158,9 +331,6 @@ stages:
   triggers:
   - type: stage
   properties:
-  - name: AIF_URL
-    value: ${AIF_URL}
-    type: text
   - name: CLOUDANT_URL
     value: ${CLOUDANT_URL}
     type: text
@@ -174,15 +344,22 @@ stages:
     script: |-
       #!/bin/bash
       # ここでテストを起動します
+      
       # Jmeter の実行時のバージョンを強制的にJava8にする。
       export JAVA_HOME=/opt/IBM/java8
       export PATH=${JAVA_HOME}/bin:$PATH
+      
+      AIF_URL=$(curl -X GET ${CLOUDANT_URL}/kubernetescredential/kubecred | awk -F\"aif_url\" '{print $2}' | awk -F\" '{print $2}')
+      AIF_PORT=$(curl -X GET ${CLOUDANT_URL}/kubernetescredential/kubecred | awk -F\"aif_port\" '{print $2}' | awk -F\" '{print $2}')
+      
+      echo $WORKSPACE
       echo ======================================
       javac -version
       echo ======================================
       mvn install:install-file -Dfile=${WORKSPACE}/AIFParent/lib/com.ibm.cis.aif.jar -DgroupId=AIF -DartifactId=com.ibm.cis.aif -Dversion=1.1 -Dpackaging=jar -DgeneratePom=true
       mvn install:install-file -Dfile=${WORKSPACE}/AIFParent/lib/com.ibm.cis.aif.tools.et.jar -DgroupId=AIF -DartifactId=com.ibm.cis.aif.tools.et -Dversion=1.1 -Dpackaging=jar -DgeneratePom=true
-      mvn integration-test  -Dtarget.host=${AIF_URL} -Dtarget.port=80 -Dcom.ibm.cis.aif.sfd.CloudantAccessor.dbName=aifdump -DJMeterPath=${JMeter_Path} -Dcom.ibm.cis.aif.sfd.SFDTestCase.contextURL=${AIF_URL}/aif -Dcom.ibm.cis.aif.sfd.CloudantAccessor.url=${CLOUDANT_URL}
+      
+      mvn integration-test  -Dtarget.host=${AIF_URL} -Dtarget.port=${AIF_PORT} -Dcom.ibm.cis.aif.sfd.CloudantAccessor.dbName=aifdump -DJMeterPath=${JMeter_Path} -Dcom.ibm.cis.aif.sfd.SFDTestCase.contextURL=${AIF_URL}:${AIF_PORT}/aif -Dcom.ibm.cis.aif.sfd.CloudantAccessor.url=${CLOUDANT_URL}
     working_dir: 'SFDParent/SFDTester'
     enable_tests: true
     test_file_pattern: 'target/failsafe-reports/TEST-*.xml'
